### ISSUE TITLE
Add "GetInsightParams" endpoint

### ISSUE THREAD

**Issue by ASteinheiser** [octoblu/meshblu-connector-wemo#1]

**Comment by royvandewater** [comment]
Gonna bring my WeMo Insight plug into the office tomorrow and see if I can get this working. Looks like we'll need to add support for requesting Insight Information to [timonreinhard/wemo-client](https://github.com/timonreinhard/wemo-client) and pull request them.

**Comment by royvandewater** [comment]
Added, will only work on Insight devices though.
